Added additional param validations & minor fixes

diff --git a/MySecondScript b/MySecondScript
--- a/MySecondScript
+++ b/MySecondScript
@@ -2,7 +2,7 @@
 echo "Num of args passed: "$# # its amount of args
 if ! [ "$#" -ge 3 ]
 then
-	echo "Error! Bad params! Formatt is: cmd [output file] [extension] [path from search executed]"
+	echo "Usage: cmd [output file] [extension] [path from search executed]"
 	exit
 fi
 if ! [ -d "$3" ]
@@ -10,9 +10,15 @@ then
 	echo "Error! Bad param! 3rd param is: [path from search executed]" >&2 # redirect to thread num 2 (error)
 	exit
 fi
+# File can not exist!
+#if ! [ -f "$1" ]
+#then
+#	echo "Error! Bad param! 1st param is: [output file]" >&2 # redirect to thread num 2 (error)
+#	exit
+#fi
 if ! [[ $2 =~ ^\. ]]
 then
-	echo "Error! Bad param! 2rd param is: [extension]" >&2 # redirect to thread num 2 (error)
+	echo "Error! Bad param! 2nd param is: [extension]" >&2 # redirect to thread num 2 (error)
 	exit
 fi
 
diff --git a/MyThirdScript b/MyThirdScript
--- a/MyThirdScript
+++ b/MyThirdScript
@@ -2,7 +2,13 @@
 # check args
 if [ $# -ne 2 ]
 then
-	echo "Error: Wrong args. Formatt is: [source file] [output filename]"
+	echo "Usage: [c lang source file] [output filename]"
+	exit
+fi
+# check if input file exists
+if ! [ -f $1 ] || ! [[ $1 =~ \.c$ ]]
+then
+	echo "Error: Wrong arg. 1st arg is [c lang source file]">&2
 	exit
 fi
 # compile
@@ -10,7 +16,7 @@ gcc $1 -o $2".exe"
 # check
 if [ $? -ne 0 ]
 then
-	echo "Compilation error! Closing.."
+	echo "Compilation error! Closing..">&2
 	exit
 fi
 echo "Compilation success! Exucuting.."
